################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Thermometer-soc-Achyut/application_properties.c \
../Thermometer-soc-Achyut/cmu.c \
../Thermometer-soc-Achyut/gatt_db.c \
../Thermometer-soc-Achyut/gpio.c \
../Thermometer-soc-Achyut/i2c.c \
../Thermometer-soc-Achyut/init_app.c \
../Thermometer-soc-Achyut/init_board.c \
../Thermometer-soc-Achyut/init_mcu.c \
../Thermometer-soc-Achyut/letimer.c \
../Thermometer-soc-Achyut/main.c \
../Thermometer-soc-Achyut/pti.c \
../Thermometer-soc-Achyut/tempsen.c \
../Thermometer-soc-Achyut/timer.c 

OBJS += \
./Thermometer-soc-Achyut/application_properties.o \
./Thermometer-soc-Achyut/cmu.o \
./Thermometer-soc-Achyut/gatt_db.o \
./Thermometer-soc-Achyut/gpio.o \
./Thermometer-soc-Achyut/i2c.o \
./Thermometer-soc-Achyut/init_app.o \
./Thermometer-soc-Achyut/init_board.o \
./Thermometer-soc-Achyut/init_mcu.o \
./Thermometer-soc-Achyut/letimer.o \
./Thermometer-soc-Achyut/main.o \
./Thermometer-soc-Achyut/pti.o \
./Thermometer-soc-Achyut/tempsen.o \
./Thermometer-soc-Achyut/timer.o 

C_DEPS += \
./Thermometer-soc-Achyut/application_properties.d \
./Thermometer-soc-Achyut/cmu.d \
./Thermometer-soc-Achyut/gatt_db.d \
./Thermometer-soc-Achyut/gpio.d \
./Thermometer-soc-Achyut/i2c.d \
./Thermometer-soc-Achyut/init_app.d \
./Thermometer-soc-Achyut/init_board.d \
./Thermometer-soc-Achyut/init_mcu.d \
./Thermometer-soc-Achyut/letimer.d \
./Thermometer-soc-Achyut/main.d \
./Thermometer-soc-Achyut/pti.d \
./Thermometer-soc-Achyut/tempsen.d \
./Thermometer-soc-Achyut/timer.d 


# Each subdirectory must supply rules for building sources it contributes
Thermometer-soc-Achyut/application_properties.o: ../Thermometer-soc-Achyut/application_properties.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\uartdrv\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\halconfig\inc\hal-config" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader\api" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\drivers" -I"C:\Users\Ayush\Desktop\Achyut\app\bluetooth\common\stack_bridge" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\inc" -I"C:\Users\Ayush\Desktop\Achyut" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\common\inc" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader" -I"C:\Users\Ayush\Desktop\Achyut\platform\CMSIS\Include" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\bsp" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\halconfig" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"Thermometer-soc-Achyut/application_properties.d" -MT"Thermometer-soc-Achyut/application_properties.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Thermometer-soc-Achyut/cmu.o: ../Thermometer-soc-Achyut/cmu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\uartdrv\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\halconfig\inc\hal-config" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader\api" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\drivers" -I"C:\Users\Ayush\Desktop\Achyut\app\bluetooth\common\stack_bridge" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\inc" -I"C:\Users\Ayush\Desktop\Achyut" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\common\inc" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader" -I"C:\Users\Ayush\Desktop\Achyut\platform\CMSIS\Include" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\bsp" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\halconfig" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"Thermometer-soc-Achyut/cmu.d" -MT"Thermometer-soc-Achyut/cmu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Thermometer-soc-Achyut/gatt_db.o: ../Thermometer-soc-Achyut/gatt_db.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\uartdrv\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\halconfig\inc\hal-config" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader\api" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\drivers" -I"C:\Users\Ayush\Desktop\Achyut\app\bluetooth\common\stack_bridge" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\inc" -I"C:\Users\Ayush\Desktop\Achyut" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\common\inc" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader" -I"C:\Users\Ayush\Desktop\Achyut\platform\CMSIS\Include" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\bsp" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\halconfig" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"Thermometer-soc-Achyut/gatt_db.d" -MT"Thermometer-soc-Achyut/gatt_db.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Thermometer-soc-Achyut/gpio.o: ../Thermometer-soc-Achyut/gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\uartdrv\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\halconfig\inc\hal-config" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader\api" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\drivers" -I"C:\Users\Ayush\Desktop\Achyut\app\bluetooth\common\stack_bridge" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\inc" -I"C:\Users\Ayush\Desktop\Achyut" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\common\inc" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader" -I"C:\Users\Ayush\Desktop\Achyut\platform\CMSIS\Include" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\bsp" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\halconfig" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"Thermometer-soc-Achyut/gpio.d" -MT"Thermometer-soc-Achyut/gpio.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Thermometer-soc-Achyut/i2c.o: ../Thermometer-soc-Achyut/i2c.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\uartdrv\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\halconfig\inc\hal-config" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader\api" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\drivers" -I"C:\Users\Ayush\Desktop\Achyut\app\bluetooth\common\stack_bridge" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\inc" -I"C:\Users\Ayush\Desktop\Achyut" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\common\inc" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader" -I"C:\Users\Ayush\Desktop\Achyut\platform\CMSIS\Include" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\bsp" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\halconfig" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"Thermometer-soc-Achyut/i2c.d" -MT"Thermometer-soc-Achyut/i2c.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Thermometer-soc-Achyut/init_app.o: ../Thermometer-soc-Achyut/init_app.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\uartdrv\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\halconfig\inc\hal-config" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader\api" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\drivers" -I"C:\Users\Ayush\Desktop\Achyut\app\bluetooth\common\stack_bridge" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\inc" -I"C:\Users\Ayush\Desktop\Achyut" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\common\inc" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader" -I"C:\Users\Ayush\Desktop\Achyut\platform\CMSIS\Include" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\bsp" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\halconfig" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"Thermometer-soc-Achyut/init_app.d" -MT"Thermometer-soc-Achyut/init_app.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Thermometer-soc-Achyut/init_board.o: ../Thermometer-soc-Achyut/init_board.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\uartdrv\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\halconfig\inc\hal-config" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader\api" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\drivers" -I"C:\Users\Ayush\Desktop\Achyut\app\bluetooth\common\stack_bridge" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\inc" -I"C:\Users\Ayush\Desktop\Achyut" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\common\inc" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader" -I"C:\Users\Ayush\Desktop\Achyut\platform\CMSIS\Include" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\bsp" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\halconfig" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"Thermometer-soc-Achyut/init_board.d" -MT"Thermometer-soc-Achyut/init_board.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Thermometer-soc-Achyut/init_mcu.o: ../Thermometer-soc-Achyut/init_mcu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\uartdrv\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\halconfig\inc\hal-config" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader\api" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\drivers" -I"C:\Users\Ayush\Desktop\Achyut\app\bluetooth\common\stack_bridge" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\inc" -I"C:\Users\Ayush\Desktop\Achyut" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\common\inc" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader" -I"C:\Users\Ayush\Desktop\Achyut\platform\CMSIS\Include" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\bsp" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\halconfig" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"Thermometer-soc-Achyut/init_mcu.d" -MT"Thermometer-soc-Achyut/init_mcu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Thermometer-soc-Achyut/letimer.o: ../Thermometer-soc-Achyut/letimer.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\uartdrv\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\halconfig\inc\hal-config" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader\api" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\drivers" -I"C:\Users\Ayush\Desktop\Achyut\app\bluetooth\common\stack_bridge" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\inc" -I"C:\Users\Ayush\Desktop\Achyut" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\common\inc" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader" -I"C:\Users\Ayush\Desktop\Achyut\platform\CMSIS\Include" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\bsp" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\halconfig" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"Thermometer-soc-Achyut/letimer.d" -MT"Thermometer-soc-Achyut/letimer.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Thermometer-soc-Achyut/main.o: ../Thermometer-soc-Achyut/main.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\uartdrv\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\halconfig\inc\hal-config" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader\api" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\drivers" -I"C:\Users\Ayush\Desktop\Achyut\app\bluetooth\common\stack_bridge" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\inc" -I"C:\Users\Ayush\Desktop\Achyut" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\common\inc" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader" -I"C:\Users\Ayush\Desktop\Achyut\platform\CMSIS\Include" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\bsp" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\halconfig" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"Thermometer-soc-Achyut/main.d" -MT"Thermometer-soc-Achyut/main.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Thermometer-soc-Achyut/pti.o: ../Thermometer-soc-Achyut/pti.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\uartdrv\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\halconfig\inc\hal-config" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader\api" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\drivers" -I"C:\Users\Ayush\Desktop\Achyut\app\bluetooth\common\stack_bridge" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\inc" -I"C:\Users\Ayush\Desktop\Achyut" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\common\inc" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader" -I"C:\Users\Ayush\Desktop\Achyut\platform\CMSIS\Include" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\bsp" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\halconfig" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"Thermometer-soc-Achyut/pti.d" -MT"Thermometer-soc-Achyut/pti.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Thermometer-soc-Achyut/tempsen.o: ../Thermometer-soc-Achyut/tempsen.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\uartdrv\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\halconfig\inc\hal-config" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader\api" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\drivers" -I"C:\Users\Ayush\Desktop\Achyut\app\bluetooth\common\stack_bridge" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\inc" -I"C:\Users\Ayush\Desktop\Achyut" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\common\inc" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader" -I"C:\Users\Ayush\Desktop\Achyut\platform\CMSIS\Include" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\bsp" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\halconfig" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"Thermometer-soc-Achyut/tempsen.d" -MT"Thermometer-soc-Achyut/tempsen.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Thermometer-soc-Achyut/timer.o: ../Thermometer-soc-Achyut/timer.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\uartdrv\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\halconfig\inc\hal-config" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader\api" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\drivers" -I"C:\Users\Ayush\Desktop\Achyut\app\bluetooth\common\stack_bridge" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\inc" -I"C:\Users\Ayush\Desktop\Achyut" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\common\inc" -I"C:\Users\Ayush\Desktop\Achyut\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\sleep\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\src" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\Ayush\Desktop\Achyut\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Ayush\Desktop\Achyut\platform\emlib\inc" -I"C:\Users\Ayush\Desktop\Achyut\platform\bootloader" -I"C:\Users\Ayush\Desktop\Achyut\platform\CMSIS\Include" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\Ayush\Desktop\Achyut\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\Ayush\Desktop\Achyut\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\bsp" -I"C:\Users\Ayush\Desktop\Achyut\hardware\kit\common\halconfig" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"Thermometer-soc-Achyut/timer.d" -MT"Thermometer-soc-Achyut/timer.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


