################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../BLE-2/application_properties.c \
../BLE-2/cmu.c \
../BLE-2/gatt_db.c \
../BLE-2/gpio.c \
../BLE-2/i2c.c \
../BLE-2/init_app.c \
../BLE-2/init_board.c \
../BLE-2/init_mcu.c \
../BLE-2/letimer.c \
../BLE-2/main.c \
../BLE-2/pti.c \
../BLE-2/sleep.c \
../BLE-2/tempsen.c \
../BLE-2/timer.c 

OBJS += \
./BLE-2/application_properties.o \
./BLE-2/cmu.o \
./BLE-2/gatt_db.o \
./BLE-2/gpio.o \
./BLE-2/i2c.o \
./BLE-2/init_app.o \
./BLE-2/init_board.o \
./BLE-2/init_mcu.o \
./BLE-2/letimer.o \
./BLE-2/main.o \
./BLE-2/pti.o \
./BLE-2/sleep.o \
./BLE-2/tempsen.o \
./BLE-2/timer.o 

C_DEPS += \
./BLE-2/application_properties.d \
./BLE-2/cmu.d \
./BLE-2/gatt_db.d \
./BLE-2/gpio.d \
./BLE-2/i2c.d \
./BLE-2/init_app.d \
./BLE-2/init_board.d \
./BLE-2/init_mcu.d \
./BLE-2/letimer.d \
./BLE-2/main.d \
./BLE-2/pti.d \
./BLE-2/sleep.d \
./BLE-2/tempsen.d \
./BLE-2/timer.d 


# Each subdirectory must supply rules for building sources it contributes
BLE-2/application_properties.o: ../BLE-2/application_properties.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\uartdrv\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\halconfig\inc\hal-config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader\api" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\drivers" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\app\bluetooth\common\stack_bridge" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\common\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\chip\efr32" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\CMSIS\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\bsp" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\halconfig" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"BLE-2/application_properties.d" -MT"BLE-2/application_properties.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE-2/cmu.o: ../BLE-2/cmu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\uartdrv\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\halconfig\inc\hal-config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader\api" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\drivers" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\app\bluetooth\common\stack_bridge" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\common\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\chip\efr32" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\CMSIS\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\bsp" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\halconfig" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"BLE-2/cmu.d" -MT"BLE-2/cmu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE-2/gatt_db.o: ../BLE-2/gatt_db.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\uartdrv\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\halconfig\inc\hal-config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader\api" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\drivers" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\app\bluetooth\common\stack_bridge" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\common\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\chip\efr32" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\CMSIS\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\bsp" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\halconfig" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"BLE-2/gatt_db.d" -MT"BLE-2/gatt_db.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE-2/gpio.o: ../BLE-2/gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\uartdrv\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\halconfig\inc\hal-config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader\api" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\drivers" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\app\bluetooth\common\stack_bridge" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\common\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\chip\efr32" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\CMSIS\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\bsp" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\halconfig" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"BLE-2/gpio.d" -MT"BLE-2/gpio.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE-2/i2c.o: ../BLE-2/i2c.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\uartdrv\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\halconfig\inc\hal-config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader\api" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\drivers" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\app\bluetooth\common\stack_bridge" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\common\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\chip\efr32" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\CMSIS\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\bsp" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\halconfig" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"BLE-2/i2c.d" -MT"BLE-2/i2c.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE-2/init_app.o: ../BLE-2/init_app.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\uartdrv\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\halconfig\inc\hal-config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader\api" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\drivers" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\app\bluetooth\common\stack_bridge" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\common\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\chip\efr32" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\CMSIS\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\bsp" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\halconfig" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"BLE-2/init_app.d" -MT"BLE-2/init_app.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE-2/init_board.o: ../BLE-2/init_board.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\uartdrv\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\halconfig\inc\hal-config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader\api" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\drivers" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\app\bluetooth\common\stack_bridge" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\common\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\chip\efr32" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\CMSIS\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\bsp" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\halconfig" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"BLE-2/init_board.d" -MT"BLE-2/init_board.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE-2/init_mcu.o: ../BLE-2/init_mcu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\uartdrv\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\halconfig\inc\hal-config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader\api" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\drivers" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\app\bluetooth\common\stack_bridge" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\common\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\chip\efr32" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\CMSIS\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\bsp" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\halconfig" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"BLE-2/init_mcu.d" -MT"BLE-2/init_mcu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE-2/letimer.o: ../BLE-2/letimer.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\uartdrv\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\halconfig\inc\hal-config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader\api" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\drivers" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\app\bluetooth\common\stack_bridge" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\common\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\chip\efr32" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\CMSIS\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\bsp" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\halconfig" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"BLE-2/letimer.d" -MT"BLE-2/letimer.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE-2/main.o: ../BLE-2/main.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\uartdrv\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\halconfig\inc\hal-config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader\api" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\drivers" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\app\bluetooth\common\stack_bridge" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\common\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\chip\efr32" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\CMSIS\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\bsp" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\halconfig" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"BLE-2/main.d" -MT"BLE-2/main.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE-2/pti.o: ../BLE-2/pti.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\uartdrv\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\halconfig\inc\hal-config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader\api" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\drivers" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\app\bluetooth\common\stack_bridge" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\common\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\chip\efr32" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\CMSIS\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\bsp" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\halconfig" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"BLE-2/pti.d" -MT"BLE-2/pti.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE-2/sleep.o: ../BLE-2/sleep.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\uartdrv\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\halconfig\inc\hal-config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader\api" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\drivers" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\app\bluetooth\common\stack_bridge" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\common\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\chip\efr32" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\CMSIS\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\bsp" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\halconfig" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"BLE-2/sleep.d" -MT"BLE-2/sleep.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE-2/tempsen.o: ../BLE-2/tempsen.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\uartdrv\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\halconfig\inc\hal-config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader\api" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\drivers" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\app\bluetooth\common\stack_bridge" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\common\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\chip\efr32" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\CMSIS\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\bsp" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\halconfig" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"BLE-2/tempsen.d" -MT"BLE-2/tempsen.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE-2/timer.o: ../BLE-2/timer.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//util/silicon_labs/silabs_core/graphics" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/dmd" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib" -I"C:/SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.3//platform/middleware/glib/glib" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\uartdrv\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\halconfig\inc\hal-config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader\api" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\drivers" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\app\bluetooth\common\stack_bridge" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\common\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\sleep\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\src" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\radio\rail_lib\chip\efr32" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emlib\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\bootloader" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\CMSIS\Include" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\bsp" -I"C:\Users\achyu\Desktop\Assign 5\BLE-2\BLE-2\hardware\kit\common\halconfig" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"BLE-2/timer.d" -MT"BLE-2/timer.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


